const LISTMOVIE = {
  LOADING: 'LISTMOVIE_LOADING',
  FETCH_SUCCESS: 'LISTMOVIE_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTMOVIE_FETCH_FAILED',
};

const MOVIEDETAIL = {
  LOADING: 'MOVIEDETAIL_LOADING',
  FETCH_DETAIL_SUCCESS: 'MOVIEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'MOVIEDETAIL_FETCH_DETAIL_SUCCESS',
};

export { LISTMOVIE, MOVIEDETAIL };
